hatchet-dev/hatchet-python

hatchet_sdk/client.py
hatchet_sdk/clients/dispatcher.py
hatchet_sdk/hatchet.py
hatchet_sdk/loader.py
hatchet_sdk/worker.py
pyproject.toml

Listener V2 dropped the refresh interval, but there seems to be a need for some platforms to define a refresh interval to ensure a stable connection. 
fixes HAT-141

feat: configurable listener timeout

---

hatchet_sdk/__init__.py
hatchet_sdk/hatchet.py
hatchet_sdk/loader.py
pyproject.toml

Patches bug on Azure Py3.10 runtime where main event loop closes.

fix:  mange asyncio event loop

---

hatchet_sdk/clients/admin.py
pyproject.toml

Additional meta key issue 
Fixes #10

fix: 0.23.1

---

hatchet_sdk/clients/admin.py
pyproject.toml

Addresses https://discord.com/channels/1088927970518909068/1240171252023562261/1240171252023562261

fix: options can be none

---

.github/dependabot.yml
.github/workflows/auto-merge.yml

do not add python deps yet as there is no proper test suite

chore(dependabot): add config for git submodule and GH actions

---

examples/concurrency-limit-rr/worker.py
examples/concurrency-limit/worker.py
examples/manual_trigger/stream.py
examples/manual_trigger/worker.py
examples/timeout/worker.py
hatchet_sdk/__init__.py
hatchet_sdk/client.py
hatchet_sdk/clients/admin.py
hatchet_sdk/clients/dispatcher.py
hatchet_sdk/clients/run_event_listener.py
hatchet_sdk/clients/workflow_listener.py
hatchet_sdk/context.py
hatchet_sdk/worker.py
hatchet_sdk/workflow_run.py
pyproject.toml

Consolidates response of `run_workflow` to a `WorkflowRunRef` and includes a few networking reliability improvements.

fix: event streaming improvements and reliability

---

hatchet_sdk/clients/admin.py
hatchet_sdk/context.py
hatchet_sdk/worker.py
hatchet_sdk/workflow_run.py
pyproject.toml

Missing init of `self.config` in admin aio implementation.

fix: admin aio client config

---

README.md

chore: fix doc url in README.md

---

examples/fanout/trigger.py
examples/fanout/worker.py
hatchet_sdk/__init__.py
hatchet_sdk/clients/admin.py
hatchet_sdk/context.py
pyproject.toml

expose option to add additional metadata to spawn child workflow context method

feat: spawn child workflow additional meta

---

hatchet_sdk/context.py
pyproject.toml

adds json serialization for objects that are not strings and adds stack trace to failed log calls

fix: logs error and serialization

---

hatchet_sdk/clients/workflow_listener.py
pyproject.toml

Fixes more edge cases in the workflow run listener (see comments)

fix: edge cases in workflow run listener

---

hatchet_sdk/clients/rest/api/api_token_api.py
hatchet_sdk/clients/rest/api/default_api.py
hatchet_sdk/clients/rest/api/event_api.py
hatchet_sdk/clients/rest/api/github_api.py
hatchet_sdk/clients/rest/api/log_api.py
hatchet_sdk/clients/rest/api/metadata_api.py
hatchet_sdk/clients/rest/api/slack_api.py
hatchet_sdk/clients/rest/api/sns_api.py
hatchet_sdk/clients/rest/api/step_run_api.py
hatchet_sdk/clients/rest/api/tenant_api.py
hatchet_sdk/clients/rest/api/user_api.py
hatchet_sdk/clients/rest/api/worker_api.py
hatchet_sdk/clients/rest/api/workflow_api.py
hatchet_sdk/clients/rest/api/workflow_run_api.py
hatchet_sdk/clients/rest/api/workflow_runs_api.py
hatchet_sdk/clients/rest/api_client.py
hatchet_sdk/clients/rest/configuration.py
hatchet_sdk/clients/rest/models/tenant_queue_metrics.py

Tackles regenerating the auto-generated SDK Clients for the v2 release.

Regenerate SDK Clients for v2 Release

---

pyproject.toml

Forgot to bump version with the Async RESTful Client PR, doing here

Bump Version to 0.36.0

---

poetry.lock
pyproject.toml

specifically fixes an issue with tenacity's conflict with `llama_index`

Update Tenacity Dep for Version Flexibility

---

examples/fanout/stream.py
hatchet_sdk/hatchet.py
pyproject.toml

Exposes the listener client on Hatchet class

fix: expose listener on hatchet

---

generate.sh
hatchet_sdk/clients/rest/api/workflow_api.py
openapi_patch.patch

Runs a patch file to fix (hopefully) temporary issues with OpenAPI Generator in how it generates 1:1 Pydantic Models and ISO formatted datetime strings.

Patch OpenAPI Generated Code When Generating New RESTful Client Code

---

hatchet_sdk/clients/admin.py
hatchet_sdk/clients/events.py
hatchet_sdk/clients/rest/tenacity_utils.py
hatchet_sdk/clients/rest/utils.py
hatchet_sdk/context/context.py
poetry.lock
pyproject.toml

- prevent silent retries
- reraise the original error so it doesn't appear obfuscated behind a RetryError
- limit the errors we retry on to GRPC errors

Improve Tenacity Verbosity and Limit Retries to Specific Errors

---

hatchet_sdk/clients/workflow_listener.py
pyproject.toml

Downgrade this to a debug log so its not as scary (as it isnt that scary and an expected behavior)

Change Level of Retried GRPC Error Log to Debug

---

hatchet_sdk/connection.py
hatchet_sdk/loader.py

Requires setting a similar value on the server too or it'll be rejected still

Allow Settable GRPC Max Send / Receive Message Size Limits

---

.github/workflows/e2e.yaml
Caddyfile
compose.yml
examples/api/test_api.py
examples/async/test_async.py
examples/on_failure/test_on_failure.py
examples/on_failure/worker.py
hatchet_sdk/utils/tracing.py
pyproject.toml

Running tests in CI (and potentially on local, if you're so inclined) against a local Hatchet stack using Compose instead of against staging to cut out a couple of potential sources of problems (network issues, rate limiting, etc.) so tests will be more reliable (hopefully)
Main con is needing to copy down the compose file - would love input on a better way to do that if anyone has ideas!

[PROPOSAL]: Local Hatchet for Tests

---

hatchet_sdk/clients/admin.py
hatchet_sdk/clients/dispatcher/action_listener.py
hatchet_sdk/clients/dispatcher/dispatcher.py
hatchet_sdk/clients/rest/tenacity_utils.py
hatchet_sdk/context/context.py
hatchet_sdk/context/worker_context.py
hatchet_sdk/utils/tracing.py
hatchet_sdk/worker/runner/runner.py
hatchet_sdk/worker/worker.py
pyproject.toml

MyPy for Context, etc.

---

pyproject.toml

Version Fix

---

examples/cancellation/worker.py
examples/concurrency_limit_rr/worker.py
examples/delayed/worker.py
examples/manual_trigger/worker.py
examples/overrides/worker.py
examples/rate_limit/worker.py
examples/sticky_workers/worker.py

Adding `if __name__ == "__main__"` to all of our examples
[Review without whitespace](https://github.com/hatchet-dev/hatchet-python/pull/302/files?diff=unified&w=1)

Fix: Make all examples runnable

---

hatchet_sdk/clients/dispatcher/action_listener.py
pyproject.toml

Fixes:
- `action_payload` has the wrong type hint I think, so it needs to get dumped to JSON

Fix: OTel bugs
