hatchet-dev/hatchet-python

hatchet_sdk/worker.py

The Python SDK was swallowing the stack trace.
- add to logs
- add to error payload
fixes HAT-120

feat: add stack trace to error

---

examples/fanout/worker.py
hatchet_sdk/clients/dispatcher.py
hatchet_sdk/connection.py
hatchet_sdk/worker.py

Adds improvements to network reliability including: 
- Rejected heartbeats will automatically trigger a new connection request. Heartbeat rejections are a signal that either the engine is down or there isn't a listener established from the worker. 
- Sets the following channel options to match the implementation of the Typescript SDK:
```
channel_options = [
("grpc.keepalive_time_ms", 10 * 1000),
("grpc.keepalive_timeout_ms", 60 * 1000),
("grpc.client_idle_timeout_ms", 60 * 1000),
("grpc.http2.max_pings_without_data", 5),
("grpc.keepalive_permit_without_calls", 1),
]
```
- Shifts heartbeat to the main thread with an async implementation, which is necessary to interrupt asyncio event flags (which aren't multithreaded)

fix: network reliability improvements

---

hatchet_sdk/__init__.py
hatchet_sdk/client.py
hatchet_sdk/clients/run_event_listener.py
pyproject.toml

Adds back the top-level listener method to the client for streaming, along with a type-safe fix on workflow_run_id for backwards compatibility.

fix: add back listener method to client

---

hatchet_sdk/connection.py
pyproject.toml

Based on my reading of https://github.com/grpc/grpc/blob/master/doc/keepalive.md:
> This channel argument controls the maximum number of pings that can be sent when there is no data/header frame to be sent. gRPC Core will not continue sending pings if we run over the limit. Setting it to 0 allows sending pings without such a restriction. (Note that this is an unfortunate setting that does not agree with [A8-client-side-keepalive.md](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md). There should ideally be no such restriction on the keepalive ping and we plan to deprecate it in the future.)
It seems that we'll only send a maximum of 5 pings over the channel if there's no data, which isn't ideal in our case as we'd like to continue sending pings.

fix: remove max_pings_without_data python

---

pyproject.toml

Lower versions of Python don't work with our typing, and we can't support them at the moment.

fix: update requirements to indicate python version >= 3.10

---

hatchet_sdk/clients/admin.py
hatchet_sdk/context.py
pyproject.toml

Some calls of `spawn_workflow` are double-prefixing the namespace which throws a "workflow not found" error

fix: namespace propagation from spawn_workflow

---

hatchet_sdk/clients/dispatcher.py
hatchet_sdk/worker.py
pyproject.toml

Adds support for awaiting all running tasks when a sigint/sigterm handler is received. 
Note that `Unregister` (internally calling `Unsubscribe`) is called as early as possible - there need to be some small changes to the Hatchet engine so that we track a shutdown state on the workers, so that new tasks stop being assigned but old tasks continue to be assigned to the worker.

fix: wait for tasks on graceful termination

---

hatchet_sdk/hatchet.py
hatchet_sdk/worker.py
pyproject.toml

Fixes a memory leak of `Context` objects in the worker code. Refactors the worker code to use a shared cleanup method for each step run or get group key run. 
Also fixes https://github.com/hatchet-dev/hatchet/issues/689

fix: context memory leak in worker and small typing issues

---

hatchet_sdk/hatchet.py
hatchet_sdk/workflow.py

Handles steps which have an upper or lowercase. All actions are lowercased in the Hatchet engine, so we won't respect case sensitivity in the client. Step names can always be overwritten using `name=` to handle collisions.
Fixes #70

fix: handle steps with uppercase

---

hatchet_sdk/clients/workflow_listener.py
pyproject.toml

If the workflow run listener gets interrupted we'll hit a loop that constantly attempts to retry

fix: retry listener delay

---

hatchet_sdk/clients/rest_client.py
hatchet_sdk/worker.py
pyproject.toml

Adds a method for cancellation that can be called via `hatchet.rest.workflow_run_cancel(workflowRun.workflow_run_id)`.

feat: cancel via rest api

---

hatchet_sdk/client.py
hatchet_sdk/hatchet.py
hatchet_sdk/worker.py
pyproject.toml

Fixes #65
This is a sketch of how a minimally intrusive version of this could work.
The default behavior is left intact, but you can use `new_from_config` to avoid the configuration from the environment.

Allow circumvention of configuration from environment with a classmethod/parameter to init

---

hatchet_sdk/clients/dispatcher.py
hatchet_sdk/hatchet.py
hatchet_sdk/logger.py
pyproject.toml

Loguru having a single configuration/logger object was causing issues when called by users. This replaces our debug logger with a std logger.

chore: remove loguru in favor of std logger

---

hatchet_sdk/clients/events.py
pyproject.toml

Example usage:
```py
event = client.event.push("user:create", {"test": "test"})
print(event.eventId)
```

feat: return event after push

---

hatchet_sdk/clients/workflow_listener.py
pyproject.toml

In the workflow run listener, not cleaning up `self.listener` was causing an issue where `.result()` on a child workflow called a second time would hang forever.

fix: remove listener ref when cleaning up subscriptions

---

hatchet_sdk/hatchet.py
hatchet_sdk/logger.py
pyproject.toml

Don't propagate hatchet logs to a root logger instance, which will lead to duplicated logging.

fix: don't propagate hatchet logs to root

---

hatchet_sdk/worker/action_listener_process.py
hatchet_sdk/worker/runner/run_loop_manager.py
hatchet_sdk/worker/worker.py

Note: This exposes a weird multiprocessing error that I have no strong leads on how to tackle.
```
Error in sys.excepthook:
Original exception was:
```
I tried to silence it as well and couldnt find where it bubbled up from.

Wait for Tasks to Complete Before Shutting Down

---

hatchet_sdk/workflow_run.py

Runs the Async Coroutines in a threadsafe loop. Allows `ref.result()` calls to be made in a non AsyncIO context when calling `ref.sync_result()`

Add Sync-Compatible Result Function

---

examples/on_failure/test_on_failure.py
examples/on_failure/worker.py
hatchet_sdk/context/context.py
hatchet_sdk/worker/runner/runner.py
pyproject.toml

Particularly helpful when utilizied in `on_failure_step`, this allows you to easily fetch the workflow run's past errors so as to see if a step raised an exception, there was a timeout, etc.

Expose Workflow Run Step Error in Runner Context

---

examples/affinity-workers/worker.py
hatchet_sdk/clients/rest_client.py
pyproject.toml

```
File ~/Library/Caches/pypoetry/virtualenvs/railbird-pQIr3DSd-py3.11/lib/python3.11/site-packages/hatchet_sdk/clients/rest_client.py:136, in AsyncRestApi.workflow_run_list(self, workflow_id, offset, limit, event_id, parent_workflow_run_id, parent_step_run_id, statuses, kinds, additional_metadata, order_by_field, order_by_direction)
122 async def workflow_run_list(
123     self,
124     workflow_id: str | None = None,
(...)
134     order_by_direction: WorkflowRunOrderByDirection | None = None,
135 ) -> WorkflowRunList:
--> 136     return await self.workflow_run_api.workflow_run_list(
137         tenant=self.tenant_id,
138         offset=offset,
139         limit=limit,
140         workflow_id=workflow_id,
141         event_id=event_id,
142 …
```

bug: workflow_run_list belongs to WorkflowApi not WorkflowRunApi

---

examples/durable_sticky_with_affinity/worker.py
hatchet_sdk/clients/dispatcher/dispatcher.py
hatchet_sdk/context/worker_context.py
hatchet_sdk/v2/callable.py
hatchet_sdk/v2/hatchet.py
hatchet_sdk/worker/action_listener_process.py
hatchet_sdk/worker/worker.py

Fixes a ton of bugs around combination usage of sticky workers, labels, and durable functions.
Adds in an ultra-cursed example of all 3 being used to limit a workflow run to a single runner per worker

Improve Usage of Sticky, Labels, and Durable

---

hatchet_sdk/hatchet.py
pyproject.toml

Should let people easily access `tenant_id` as an example.

Expose Client Config in SDK Main Class

---

hatchet_sdk/clients/dispatcher/dispatcher.py
hatchet_sdk/worker/action_listener_process.py
pyproject.toml

Handles a case where sending a succeeded event payload fails due to serialization errors, payload too large, etc. This will now send a proper stack trace to Hatchet to track these failures.

fix: send failure events when we cannot send a succeeded or failed event

---

hatchet_sdk/clients/admin.py
hatchet_sdk/clients/dispatcher/action_listener.py
hatchet_sdk/clients/dispatcher/dispatcher.py
hatchet_sdk/clients/rest/tenacity_utils.py
hatchet_sdk/context/context.py
hatchet_sdk/context/worker_context.py
hatchet_sdk/hatchet.py
hatchet_sdk/utils/tracing.py
hatchet_sdk/worker/runner/runner.py
hatchet_sdk/worker/worker.py
hatchet_sdk/workflow.py
pyproject.toml

MyPy fixes for the `Workflow` metaclass and some downstream usage with a protocol

MyPy, Part II or III: `Workflow` metaclass

---

.github/workflows/lint.yaml
examples/pydantic/test_pydantic.py
examples/pydantic/trigger.py
examples/pydantic/worker.py
hatchet_sdk/clients/admin.py
hatchet_sdk/clients/dispatcher/action_listener.py
hatchet_sdk/clients/dispatcher/dispatcher.py
hatchet_sdk/clients/rest/tenacity_utils.py
hatchet_sdk/context/context.py
hatchet_sdk/context/worker_context.py
hatchet_sdk/hatchet.py
hatchet_sdk/utils/backoff.py
hatchet_sdk/utils/serialization.py
hatchet_sdk/utils/tracing.py
hatchet_sdk/utils/types.py
hatchet_sdk/utils/typing.py
hatchet_sdk/v2/callable.py
hatchet_sdk/worker/action_listener_process.py
hatchet_sdk/worker/runner/run_loop_manager.py
hatchet_sdk/worker/runner/runner.py
hatchet_sdk/worker/worker.py
hatchet_sdk/workflow.py
lint.sh
pyproject.toml

A couple things here:
* AFAICT, `Worker` doesn't need to be a `dataclass`, and this was making things a bit more complicated (b/c of `post_init`, etc.)
* Added `hatchet_sdk/worker/worker.py` to the included MyPy paths and fixed all the type hints (except for a couple tricky ones with the `WorkflowMeta` metaclass - we can handle those later
* Replaced some dynamically set attributes with `setattr` to make the type checker happy
* Added a `Protocol` for the `WorkflowMeta` metaclass for the same reason
* Fixes for `Workflow` metaclass and `Context`
Will try to annotate!

MyPy Fixes for `Worker`, `Workflow` metaclass, `Context`, and some others

---

hatchet_sdk/loader.py
hatchet_sdk/worker/worker.py
poetry.lock
pyproject.toml

Adding a simple server to handle worker health checks using `aiohttp` running on a customizable port w/ a default.
Example requests:
`/health` (basic usage)
```bash
hatchet-sdk-py3.10matt@Mac hatchet-python % curl localhost:8001/health 
{"status": "HEALTHY"}%   
```
`/metrics` (Prometheus)
```bash
hatchet-sdk-py3.10matt@Mac hatchet-python % curl localhost:8001/metrics
python_gc_objects_collected_total{generation="0"} 18641.0
python_gc_objects_collected_total{generation="1"} 4788.0
python_gc_objects_collected_total{generation="2"} 215.0
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
python_gc_collections_total{generation="0"} 308.0 …
```

Feat: Worker Health Checks

---

.gitignore
hatchet_sdk/clients/admin.py
hatchet_sdk/clients/events.py
hatchet_sdk/clients/rest/tenacity_utils.py
pyproject.toml

Fixing Tenacity logic for retries here - there were a couple of issues:
1. It's not super clear to me when `grpc` will raise a `grpc.RpcError` vs when it will raise `grpc.aio.AioRpcError` (I'd think that when using `aio` methods it'd raise an `aio` error, but from local testing that appears to not be the case. So I just am catching both cases everywhere for now.
2. We were catching these RPC errors and re-raising value errors in a number of places, which would cause the `isinstance(ex, (grpc.aio.AioRpcError, grpc.RpcError))` check to fail, making the errors fall through and not be retried. In those cases, I removed the error handling in the function that had retries enabled (cc @grutt lmk if there's a reason I'm missing for doing this - want to make sure I'm not breaking something …

Fix Tenacity Retry Logic

---

examples/on_failure/worker.py
hatchet_sdk/context/context.py
pyproject.toml

Intended to be used in an on-failure step

Feat: Expose step run errors on context

---

examples/cron/programatic-async.py
examples/cron/programatic-sync.py
hatchet_sdk/clients/rest_client.py
pyproject.toml

Trying to create a dynamic cron will fail b/c of this misnamed param

Fix: Dynamic Crons Pydantic Key Error

---

hatchet_sdk/clients/rest_client.py
pyproject.toml

Fixing error
```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for scheduled_workflow_run_create
schedule_workflow_run_request
Missing required argument [type=missing_argument, input_value=ArgsKwargs((<hatchet_sdk....atetime.timezone.utc))}), input_type=ArgsKwargs]
For further information visit https://errors.pydantic.dev/2.9/v/missing_argument
create_schedule_workflow_trigger_request
Unexpected keyword argument [type=unexpected_keyword_argument, input_value=ScheduleWorkflowRunReques...=datetime.timezone.utc)), input_type=ScheduleWorkflowRunRequest]
For further information visit https://errors.pydantic.dev/2.9/v/unexpected_keyword_argument
```
Context: https://discord.com/channels/1088927970518909068/1331373228161237013
Related: …

Fix: Create Schedule Workflow Pydantic Key Error 

---

hatchet_sdk/clients/dispatcher/dispatcher.py
hatchet_sdk/loader.py
pyproject.toml

Adds autoscaling target config loading

feat: add autoscaling target config

---

hatchet_sdk/clients/admin.py
pyproject.toml

The inplace modification of `option` object in `_prepare_workflow_request` is causing a bug.
If an error occurrs after `_prepare_workflow_request` returns but before new workflows are spawned, then tenacity retries will happen with options dict modified. This is a huge problem when you have any `additional_metadata` set, because it is going to be a binary in any of the retries (instead of a string).
**(I am having some problems in production beacause of it, so it would be very nice to have this resolved asap)**
FYI @mmacvicar @banduk @ArthurMor4is @vncsna @cezarguimaraes 
Modify `AdminClientAioImpl.run_workflows` to raise an error after calling `_prepare_workflow_request`.
Trigger a workflow that uses `spawn_workflows` and receives some additional_metadata.
In the first attempt, your new …

fix: removes in-place modification of `options` in `_prepare_workflow_request`

---

examples/opentelemetry_instrumentation/test_otel_instrumentation.py
examples/opentelemetry_instrumentation/triggers.py
hatchet_sdk/opentelemetry/instrumentor.py
pyproject.toml

Fixing a couple more OTel things:
1. Exporting helpers outside of the instrumentor instance
2. Docs
3. Defaulting to current span if no parent is specified

Fix: More OTel Cleanup

---

poetry.lock
pyproject.toml

Bumping min `celpy` version for `lark` compat
see https://github.com/cloud-custodian/cel-python/pull/82

Fix: Bump min `celpy` version

---

hatchet_sdk/worker/runner/runner.py

Enables killing sync threads on cancellation signals being received so sync tasks stop instead of running to completion

Feat: Killing sync threads

---

hatchet_sdk/clients/rest_client.py
hatchet_sdk/worker/action_listener_process.py
pyproject.toml

Pausing assignment of work to the worker when we get an exit signal

Fix: Pause Work Assignment on Exit
